# Generated by Django 3.1.6 on 2021-06-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(default='', max_length=30)),
                ('icontact', models.IntegerField(default=None)),
                ('comments', models.TextField(default='')),
                ('rate', models.CharField(choices=[('very good', 'very good'), ('weak', 'weak'), ('good', 'good'), ('poor', 'poor'), ('excellent', 'excellent')], default='', max_length=15, null=True)),
                ('typemessage', models.CharField(choices=[('Suggestion', 'Suggestion'), ('Question', 'Question'), ('Comment', 'Comment')], default='', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Psrsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completename', models.CharField(default='', max_length=50, null=True)),
                ('address', models.TextField(default='')),
                ('occupationhead', models.CharField(default='', max_length=50)),
                ('salaryhead', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidyconfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('contact', models.IntegerField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subsidy', models.IntegerField(default='')),
                ('completename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prac.psrsignup')),
            ],
        ),
        migrations.CreateModel(
            name='Receivingplacedate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('Phase 1', 'PHASE1'), ('Phase 2', 'PHASE2'), ('Phase 3', 'PHASE3'), ('Phase 4', 'PHASE 4')], default='', max_length=50, null=True)),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
                ('completename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prac.psrsignup')),
            ],
        ),
        migrations.CreateModel(
            name='Receivingbankpawnshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_pawnshop', models.CharField(choices=[('Landbank', 'LANDBANK'), ('PNB', 'PNB'), ('MLHUILLER', 'MLHUILLER'), ('PALAWAN', 'PALAWAN')], default='', max_length=50, null=True)),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
                ('completename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prac.psrsignup')),
            ],
        ),
        migrations.CreateModel(
            name='Familyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname1', models.CharField(default='', max_length=50)),
                ('familyname2', models.CharField(default='', max_length=50)),
                ('familyname3', models.CharField(default='', max_length=50)),
                ('occupation1', models.CharField(default='', max_length=50)),
                ('occupation2', models.CharField(default='', max_length=50)),
                ('occupation3', models.CharField(default='', max_length=50)),
                ('salary1', models.IntegerField(default='')),
                ('salary2', models.IntegerField(default='')),
                ('salary3', models.IntegerField(default='')),
                ('totalsalary', models.IntegerField(default='')),
                ('completename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prac.psrsignup')),
            ],
        ),
    ]
